development:
  adapter: postgresql
  encoding: unicode
  database: movienight_development
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: movienight_production
  pool: 5
  username: postgres
  password:
